const express = require('express');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const db = require('../db');
const { requireAuth } = require('../middleware/auth');

const router = express.Router();

const BACKUP_DIR = path.join(__dirname, '..', 'backups');
const BACKUP_SECRET = process.env.BACKUP_SECRET_KEY || process.env.JWT_SECRET || 'fst_guest_mgmt_backup_secret_2026_default!';

// Helper function to encrypt text using AES-256-CBC
function encrypt(text) {
  // Use SHA256 to derive a 32-byte key from the secret
  const key = crypto.createHash('sha256').update(String(BACKUP_SECRET)).digest();
  const iv = crypto.randomBytes(16);
  const cipher = crypto.createCipheriv('aes-256-cbc', key, iv);
  let encrypted = cipher.update(text, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  return iv.toString('hex') + ':' + encrypted;
}

// Helper function to decrypt text using AES-256-CBC
function decrypt(ciphertext) {
  try {
    const key = crypto.createHash('sha256').update(String(BACKUP_SECRET)).digest();
    const parts = ciphertext.split(':');
    if (parts.length !== 2) return null;
    const iv = Buffer.from(parts[0], 'hex');
    const encryptedText = Buffer.from(parts[1], 'hex');
    const decipher = crypto.createDecipheriv('aes-256-cbc', key, iv);
    let decrypted = decipher.update(encryptedText, 'hex', 'utf8');
    decrypted += decipher.final('utf8');
    return decrypted;
  } catch (err) {
    console.error('Backup decryption failed:', err.message);
    return null;
  }
}

// Auto backup generator helper
async function generateBackupData() {
  const [users] = await db.query('SELECT * FROM users');
  const [guests] = await db.query('SELECT * FROM guests');
  const [statusHistory] = await db.query('SELECT * FROM status_history');
  const [settings] = await db.query('SELECT * FROM settings');

  return {
    version: '1.0.0',
    timestamp: new Date().toISOString(),
    tables: {
      users,
      guests,
      status_history: statusHistory,
      settings
    }
  };
}

// Write backup to local folder
async function runAutoBackup() {
  try {
    if (!fs.existsSync(BACKUP_DIR)) {
      fs.mkdirSync(BACKUP_DIR);
    }

    const data = await generateBackupData();
    const now = new Date();
    const dateStr = now.toISOString().replace(/T/, '_').replace(/\..+/, '').replace(/:/g, '-');
    const filename = `backup-auto-${dateStr}.bak`;
    const filepath = path.join(BACKUP_DIR, filename);

    // Encrypt backup contents
    const encryptedText = encrypt(JSON.stringify(data));
    fs.writeFileSync(filepath, encryptedText, 'utf8');
    console.log(`Automatic database backup successfully saved: ${filename}`);

    // Rotation: keep last 10 automatic backups
    const files = fs.readdirSync(BACKUP_DIR)
      .filter(f => f.startsWith('backup-auto-') && f.endsWith('.bak'))
      .map(f => ({ name: f, stat: fs.statSync(path.join(BACKUP_DIR, f)) }))
      .sort((a, b) => b.stat.mtime - a.stat.mtime);

    if (files.length > 10) {
      for (let i = 10; i < files.length; i++) {
        fs.unlinkSync(path.join(BACKUP_DIR, files[i].name));
        console.log(`Rotated/deleted old automatic backup: ${files[i].name}`);
      }
    }
  } catch (err) {
    console.error('Failed to run automatic backup:', err.message);
  }
}

// Schedule daily automatic backups (every 24 hours)
setInterval(runAutoBackup, 24 * 60 * 60 * 1000);

// Apply requireAuth to all endpoints below
router.use(requireAuth);

// Protected Export Endpoint
router.get('/export', async (req, res) => {
  try {
    const data = await generateBackupData();
    const encryptedText = encrypt(JSON.stringify(data));
    res.setHeader('Content-disposition', `attachment; filename=backup-manual-${Date.now()}.bak`);
    res.setHeader('Content-type', 'text/plain');
    res.send(encryptedText);
  } catch (err) {
    console.error('Backup export error:', err.message);
    res.status(500).json({ error: 'Failed to generate backup export.' });
  }
});

// Protected Import/Restore Endpoint
router.post('/import', async (req, res) => {
  const { encryptedData } = req.body;
  if (!encryptedData) {
    return res.status(400).json({ error: 'No backup data provided' });
  }

  const decryptedText = decrypt(encryptedData);
  if (!decryptedText) {
    return res.status(400).json({ error: 'Decryption failed. The backup file is invalid, corrupt, or was generated by a different system/secret key.' });
  }

  let data;
  try {
    data = JSON.parse(decryptedText);
  } catch (e) {
    return res.status(400).json({ error: 'Failed to parse decrypted backup JSON.' });
  }

  const { tables } = data;
  if (!tables || !tables.users || !tables.guests || !tables.status_history || !tables.settings) {
    return res.status(400).json({ error: 'Invalid backup file structure.' });
  }

  const conn = await db.getPool().getConnection();
  try {
    await conn.beginTransaction();

    // Disable foreign key checks
    await conn.query('SET FOREIGN_KEY_CHECKS = 0');

    // Delete existing records (DML so it respects transaction rollback)
    await conn.query('DELETE FROM status_history');
    await conn.query('DELETE FROM guests');
    await conn.query('DELETE FROM settings');
    await conn.query('DELETE FROM users');

    // Restore users
    for (const u of tables.users) {
      await conn.query(
        'INSERT INTO users (id, username, password, created_at, updated_at) VALUES (?, ?, ?, ?, ?)',
        [u.id, u.username, u.password, u.created_at, u.updated_at]
      );
    }

    // Restore settings
    for (const s of tables.settings) {
      await conn.query(
        'INSERT INTO settings (id, setting_key, setting_value) VALUES (?, ?, ?)',
        [s.id, s.setting_key, s.setting_value]
      );
    }

    // Restore guests
    for (const g of tables.guests) {
      await conn.query(
        `INSERT INTO guests 
         (id, name, id_num, doc_type, nationality, dob, expiry_date, phone, raw_data, photo, checked_in, check_in_time, saved_date, hidden, status, warning_date, warning_reason, blocked_date, blocked_reason, deleted, delete_reason, deleted_at, created_at, updated_at) 
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          g.id, g.name, g.id_num, g.doc_type, g.nationality, g.dob, g.expiry_date, g.phone, g.raw_data, g.photo, 
          g.checked_in, g.check_in_time, g.saved_date, g.hidden, g.status, g.warning_date, g.warning_reason, 
          g.blocked_date, g.blocked_reason, g.deleted !== undefined ? g.deleted : 0, g.delete_reason || null, 
          g.deleted_at || null, g.created_at, g.updated_at
        ]
      );
    }

    // Restore status_history
    for (const h of tables.status_history) {
      await conn.query(
        'INSERT INTO status_history (id, guest_id, type, reason, date, by_user, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)',
        [h.id, h.guest_id, h.type, h.reason, h.date, h.by_user, h.created_at]
      );
    }

    // Re-enable foreign key checks
    await conn.query('SET FOREIGN_KEY_CHECKS = 1');

    await conn.commit();
    res.json({ message: 'Database successfully restored from backup' });
  } catch (err) {
    await conn.rollback();
    console.error('Import backup error:', err.message);
    res.status(500).json({ error: 'Failed to restore database from backup file.' });
  } finally {
    try {
      await conn.query('SET FOREIGN_KEY_CHECKS = 1');
    } catch (e) {
      console.error('Error re-enabling foreign key checks:', e.message);
    }
    conn.release();
  }
});

// Protected List Backups Endpoint
router.get('/list', async (req, res) => {
  try {
    if (!fs.existsSync(BACKUP_DIR)) {
      fs.mkdirSync(BACKUP_DIR);
    }
    const files = fs.readdirSync(BACKUP_DIR)
      .filter(f => f.endsWith('.bak'))
      .map(f => {
        const stats = fs.statSync(path.join(BACKUP_DIR, f));
        return {
          filename: f,
          size: stats.size,
          createdAt: stats.mtime
        };
      })
      .sort((a, b) => b.createdAt - a.createdAt);

    res.json({ backups: files });
  } catch (err) {
    console.error('List backups error:', err.message);
    res.status(500).json({ error: 'Failed to retrieve backups list.' });
  }
});

module.exports = {
  router,
  runAutoBackup
};
